- id: doi:10.1145/3620666.3651382
- title: "KeyTAR: Practical Keystroke Timing Attacks and Input Reconstruction"
  authors: 
    - "Mufan Qiu*"
    - "Lihsuan Chuang*" 
    - Dohhyun Kim
    - Huaizhi Qu
    - Andrew Kwong 
    - Tianlong Chen
  publisher: 47th IEEE Symposium on Security and Privacy 
  date: 2026-05-18
  link: jameschuang2002.github.io/keytar.pdf
